version: '3.8'

services:
    mcrusers:
        image: buckybuck/mcrusers
        container_name: mcrusers
        ports:
          - "8081:8081"
        depends_on:
          - db
        environment:
          - MONGO_USERNAME=db
          - MONGO_PASSWORD=db
          - MONGO_HOSTNAME=db
          - MONGO_PORT=27017
          - MONGO_DB=microservices
        networks:
          - app-network
    
    mcrquotas:
        image: buckybuck/mcrquotas
        container_name: mcrquotas
        ports:
          - "8082:8082"
        depends_on:
          - db
        environment:
          - MONGO_USERNAME=db
          - MONGO_PASSWORD=db
          - MONGO_HOSTNAME=db
          - MONGO_PORT=27017
          - MONGO_DB=microservices
        networks:
          - app-network

    vue:
        image: buckybuck/mcrvue
        container_name: vue
        ports:
          - "80:80"
        depends_on:
          - nodejs
        networks:
          - app-network
    
    db:
        image: mongo
        container_name: mongo
        networks:
          - app-network
        ports:
          - "27017:27017"
        command: [--auth]
        environment:
          - MONGO_INITDB_ROOT_USERNAME=db
          - MONGO_INITDB_ROOT_PASSWORD=db

networks:
    app-network:
        driver: bridge
