apiVersion: v1
kind: Service
metadata:
  name: gui-app-service
  labels:
    app: gui-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: gui-app
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gui-app
  name: gui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gui-app
    spec:
      containers:
        - name: gui
          image: gui
          ports:
            - containerPort: 80
              name: gui
          env:
            - name: VUE_APP_BASE_URL
              value: 34.140.9.12
            - name: VUE_APP_BASE_PROTOCOL
              value: "http"
    